### ISSUE TITLE
Newsletter architecture

### ISSUE THREAD

**Issue by lagolucas** [projeto7c0/projeto7c0.github.io#2]
Creation of the structure necessary to capture email adrresses of interested people.
To eventually create a newsletter.

**Comment by bertassi** [comment]
First of all, it is necessary to create a MailChimp (or similar) account. Second, create a subscription form so that the code can be embedded, in the HTML code. For more details, check: [MailChimp - Add a Signup Form to Your Website](https://mailchimp.com/help/add-a-signup-form-to-your-website/).

The idea is to use the "Horizontal Form" option. It only includes an email address field.

**Comment by bertassi** [comment]
Done! The newsletter functionality is integrated with MailChimp (with reCaptcha) and all default MailChimp forms are internationalized, i.e., they present their content in English or Portuguese depending on the users' location.
